name: Auto Branch Sync

on:
  pull_request:
    types: [closed]
    branches:
      - release  # Trigger only when PRs into `release` are merged

jobs:
  sync_branches:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Push main to master
        run: |
          git fetch origin
          git checkout main
          git push origin main:master --force

      - name: Sync release to main
        run: |
          git fetch origin
          git checkout release
          git merge main --no-edit
          git push origin release

          git checkout main
          git merge release --no-edit
          git push origin main

