name: Auto Branch Sync

on:
  pull_request:
    types: [closed]
    branches:
      - release  # Trigger only when PRs into `release` are merged

jobs:
  sync_branches:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}
          persist-credentials: true

      - name: Set up Git
        run: |
          git config user.name "rdx40"
          git config user.email "ivanjaison@gmail.com"

      - name: Push main to master
        run: |
          git fetch origin
          git checkout main
          git push origin main:master --force

      - name: Force push main to release
        run: |
          git fetch origin
          git checkout main
          git push origin main:release --force

      - name: Force push release back to main (optional)
        run: |
          git fetch origin
          git checkout release
          git push origin release:main --force
